francis_exam_onboarding/bulletin/urls.py
from django.conf.urls import url, include

from django.contrib.auth import views as auth_views

from . import views as bulletin_views

app_name = 'bulletin'

board_patterns = [
    url(r'^create$', bulletin_views.CreateBoard.as_view(), name='create_board'),
    url(r'^(?P<pk>[0-9]+)$', bulletin_views.board_first_page, name='view_board'),
    url(r'^(?P<pk>[0-9]+)/page-(?P<page>[0-9]+)/$', bulletin_views.ViewBoard.as_view(), name='view_board_page'),
    url(r'^(?P<pk>[0-9]+)/edit/$', bulletin_views.EditBoard.as_view(), name='edit_board'),
    url(r'^delete/$', bulletin_views.DeleteBoard.as_view() , name='delete_board'),
]

thread_patterns = [
    url(r'^create/(?P<pk>[0-9]+)$', bulletin_views.CreateThread.as_view(), name='create_thread'),
    url(r'^(?P<pk>[0-9]+)/$', bulletin_views.thread_first_page, name='view_thread'),
    url(r'^(?P<pk>[0-9]+)/page-(?P<page>[0-9]+)/$', bulletin_views.ViewThread.as_view(), name='view_thread_page'),
    url(r'^(?P<pk>[0-9]+)/edit/$', bulletin_views.EditThread.as_view(), name='edit_thread'),
    url(r'^(?P<pk>[0-9]+)/create-post/$', bulletin_views.create_post, name='create_post'),
]

urlpatterns = [
    url(r'^$', bulletin_views.index_first_page , name='index'),
    url(r'^page-(?P<page>[0-9]+)/$', bulletin_views.IndexView.as_view() , name='view_index_page'),
    url(r'^login/$', auth_views.login, {'template_name':'bulletin/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name':'bulletin/logout.html'}, name='logout'),
    url(r'^register/$', bulletin_views.register , name='register'),
    url(r'^board/', include(board_patterns)),
    url(r'^thread/', include(thread_patterns)),
    url(r'^profiles/(?P<pk>[0-9]+)/$', bulletin_views.profile_first_page, name='view_profile'),
    url(r'^profiles/(?P<pk>[0-9]+)/page-(?P<page>[0-9]+)$', bulletin_views.ViewUserProfile.as_view(), name='view_profile_page'),
    url(r'^profiles/(?P<pk>[0-9]+)/set-ban/(?P<is_ban>[\w]+)$', bulletin_views.set_user_ban, name='set_user_ban'),
]

francis_exam_onboarding/francis_exam_onboarding/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views as root_views

urlpatterns = [
    url(r'^$', root_views.redirect_root),
    url(r'^admin/', admin.site.urls),
    url(r'^bulletin/', include('bulletin.urls')),
]

francis_exam_onboarding/bulletin/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save

# Create your models here.


class Board(models.Model):
    name = models.CharField(max_length=200)
    creator = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    created_on = models.DateTimeField(auto_now_add=True)
    position = models.PositiveIntegerField(default=0)

    def get_recent_post(self):
        posts = self.post_set.all().order_by("-posted_on")
        if posts.count() > 0:
            return posts[0]
        else:
            return None


class Thread(models.Model):
    title = models.CharField(max_length=200)
    board = models.ForeignKey(Board, on_delete=models.DO_NOTHING)
    posted_by = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    posted_on = models.DateTimeField(auto_now_add=True)
    is_locked = models.BooleanField(default=False)

    def get_recent_post(self):
        posts = self.post_set.all().order_by("-posted_on")
        if posts.count() > 0:
            return posts[0]
        else:
            return None
    def get_recent_poster_profile_id(self):
        posts = self.post_set.all().order_by("-posted_on")
        if posts.count() > 0:
            return posts[0].posted_by.userprofile.id
        else:
            return None


class Post(models.Model):
    message = models.CharField(max_length=10000)
    thread = models.ForeignKey(Thread, on_delete=models.DO_NOTHING)
    board = models.ForeignKey(Board, on_delete=models.DO_NOTHING)
    posted_on = models.DateTimeField(auto_now_add=True)
    posted_by = models.ForeignKey(User, on_delete=models.DO_NOTHING)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_banned = models.BooleanField(default=False)


def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])


post_save.connect(create_profile, sender=User)

francis_exam_onboarding/bulletin/forms.py
from django import forms
from django.contrib.auth.models import User, Group
from django.contrib.auth.forms import (
    UserCreationForm,
    UserChangeForm,
    PasswordChangeForm,
)

from .models import Board, Thread, Post, UserProfile


class RegistrationForm(UserCreationForm):
    groups = forms.ModelChoiceField(queryset=Group.objects.all())

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
            'groups',
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        user.is_active = True

        if commit:
            user.save()
            user_group = self.cleaned_data['groups']
            user_group.user_set.add(user)


        return user


class BoardForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ['name', 'position']


class ThreadForm(forms.ModelForm):
    class Meta:
        model = Thread
        fields = ['title', 'is_locked']


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['message']
        widgets = {
            'message': forms.Textarea(attrs={'rows': 3, 'style': 'width:100%'})
        }

francis_exam_onboarding/bulletin/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.paginator import Paginator

from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

from .templatetags import bulletin_extras


from .forms import RegistrationForm, BoardForm, ThreadForm, PostForm

from .models import Board, Thread, Post, UserProfile


# Create your views here.
class UserPermissionsMixin(object):
    """Mixin to provide access to Users Permissions"""
    user = None

    @property
    def is_admin(self):
        if self.user != None:
            return bulletin_extras.is_admin(self.user)
        else:
            return False

    @property
    def is_mod(self):
        if self.user != None:
            return bulletin_extras.is_mod(self.user)
        else:
            return False

    @property
    def is_banned(self):
        if self.user != None:
            return self.user.userprofile.is_banned
        else:
            return False


class PaginationMixin(object):
    main_list = []
    number_of_contents_per_list = 20

    @property
    def get_paginator(self):
        return Paginator(self.main_list, self.number_of_contents_per_list)


class BaseView(LoginRequiredMixin, UserPermissionsMixin, generic.View):
    login_url = '/bulletin/login/'
    redirect_field_name = 'redirect_to'


class IndexView(PaginationMixin, BaseView):
    def get(self, request, *args, **kwargs):
        self.user = request.user
        page_number = self.kwargs['page']
        self.main_list = Board.objects.all().order_by('position')
        list_paginator = self.get_paginator
        page_count = list_paginator.num_pages
        if int(page_number) > page_count:
            return redirect(reverse("bulletin:view_index_page", args=(page_count,)))
        args = {'is_banned': self.is_banned,
                'page_object': list_paginator.page(page_number),
                'page_count': page_count,
                'page_number': int(page_number), }
        return render(request, 'bulletin/home.html', args)


class CreateBoard(BaseView):
    def get(self, request, *args, **kwargs):
        self.user = request.user
        if self.is_admin and not self.is_banned:
            form = BoardForm()
            form.creator = request.user
            args = {'form': form}
            return render(request, 'bulletin/create_board.html', args)
        else:
            return redirect(reverse("bulletin:index"))

    def post(self, request, *args, **kwargs):
        form = BoardForm(request.POST)
        if form.is_valid():
            new_board = form.save(commit=False)
            new_board.creator = request.user
            new_board.save()
            return redirect(reverse("bulletin:view_board", args=(new_board.pk,)))
        else:
            args = {'form': form}
            return render(request, 'bulletin/create_board.html', args)


class EditBoard(BaseView):
    def get(self, request, *args, **kwargs):
        self.user = request.user
        pk = self.kwargs['pk']
        if self.is_admin and not self.is_banned:
            board = get_object_or_404(Board, pk=pk)
            form = BoardForm(instance=board)
            args = {'form': form}
            return render(request, 'bulletin/edit_board.html', args)
        else:
            return redirect(reverse("bulletin:view_board", args=(pk,)))

    def post(self, request, *args, **kwargs):
        pk = self.kwargs['pk']
        board = get_object_or_404(Board, pk=pk)
        form = BoardForm(request.POST, instance=board)
        if form.is_valid():
            form.save()
            return redirect(reverse('bulletin:view_board', args=(pk,)))
        else:
            args = {'form': form}
            return render(request, 'bulletin/edit_board.html', args)


class ViewBoard(PaginationMixin, BaseView):
    def get(self, request, *args, **kwargs):
        self.user = request.user
        pk = self.kwargs['pk']
        page_number = self.kwargs['page']
        board = get_object_or_404(Board, pk=pk)
        self.main_list = board.thread_set.all().order_by("-posted_on")
        list_paginator = self.get_paginator
        page_count = list_paginator.num_pages
        if int(page_number) > page_count:
            return redirect(reverse("bulletin:view_board_page", args=(pk, page_count,)))
        args = {'board': board, 'is_banned': self.is_banned,
                'page_object': list_paginator.page(page_number),
                'page_count': list_paginator.num_pages,
                'page_number': int(page_number)}
        return render(request, 'bulletin/view_board.html', args)


class DeleteBoard(BaseView):
    def post(self, request, *args, **kwargs):
        self.user = request.user
        pk = request.POST['delete_board_id']
        if self.is_admin and not self.is_banned:
            Board.objects.filter(pk=pk).delete()
        return redirect(reverse("bulletin:index"))


class CreateThread(BaseView):
    def get(self, request, *args, **kwargs):
        form = ThreadForm()
        args = {'form': form}
        return render(request, 'bulletin/create_thread.html', args)

    def post(self, request, *args, **kwargs):
        form = ThreadForm(request.POST)
        pk = self.kwargs['pk']
        board = get_object_or_404(Board, pk=pk)
        if form.is_valid():
            new_thread = form.save(commit=False)
            new_thread.board = board
            new_thread.posted_by = request.user
            new_thread.save()
            return redirect(reverse("bulletin:view_thread", args=(new_thread.pk,)))
        else:
            args = {'form': form}
            return render(request, 'bulletin/create_thread.html', args)


class EditThread(BaseView):
    def get(self, request, *args, **kwargs):
        pk = self.kwargs['pk']
        thread = get_object_or_404(Thread, pk=pk)
        form = ThreadForm(instance=thread)
        args = {'form': form}
        return render(request, 'bulletin/edit_thread.html', args)

    def post(self, request, *args, **kwargs):
        pk = self.kwargs['pk']
        thread = get_object_or_404(Thread, pk=pk)
        form = ThreadForm(request.POST, instance=thread)
        if form.is_valid():
            form.save()
            return redirect(reverse("bulletin:view_thread", args=(pk,)))


class ViewThread(PaginationMixin, BaseView):
    def get(self, request, *args, **kwargs):
        pk = self.kwargs['pk']
        page_number = self.kwargs['page']
        thread = get_object_or_404(Thread, pk=pk)
        self.main_list = thread.post_set.all().order_by("posted_on")
        list_paginator = self.get_paginator
        page_count = list_paginator.num_pages
        if int(page_number) > page_count:
            return redirect(reverse("bulletin:view_thread_page", args=(pk, page_count,)))
        user = request.user
        form = PostForm()
        args = {'thread': thread, 'form': form, 'user': user,
                'page_object': list_paginator.page(page_number),
                'page_count': list_paginator.num_pages,
                'page_number': int(page_number)
                }
        return render(request, 'bulletin/view_thread.html', args)


class ViewUserProfile(PaginationMixin, BaseView):
    def get(self, request, *args, **kwargs):
        pk = self.kwargs['pk']
        page_number = self.kwargs['page']
        self.user = request.user
        is_self = request.user.userprofile.pk == int(pk)
        user_profile = get_object_or_404(UserProfile, pk=pk)
        self.main_list = user_profile.user.post_set.all().order_by("-posted_on")
        list_paginator = self.get_paginator
        page_count = list_paginator.num_pages
        if int(page_number) > page_count:
            return redirect(reverse("bulletin:view_profile_page", args=(pk, page_count,)))
        args = {'user_profile': user_profile, 'is_self': is_self, 'page_object': list_paginator.page(page_number),
                'page_count': list_paginator.num_pages,
                'page_number': int(page_number)
                }
        return render(request, 'bulletin/view_user_profile.html', args)


def register(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('bulletin:index'))
        else:
            args = {'form': form}
            return render(request, 'bulletin/register.html', args)
    else:
        form = RegistrationForm()
        args = {'form': form}
        return render(request, 'bulletin/register.html', args)


def create_post(request, pk):
    thread = get_object_or_404(Thread, pk=pk)
    form = PostForm(request.POST)
    if form.is_valid():
        new_post = form.save(commit=False)
        new_post.thread = thread
        new_post.board = thread.board
        new_post.posted_by = request.user
        new_post.save()
    return redirect(reverse("bulletin:view_thread", args=(thread.pk,)))


def set_user_ban(request, pk, is_ban):
    user_profile = get_object_or_404(UserProfile, pk=pk)
    if is_ban == "true":
        user_profile.is_banned = True
    else:
        user_profile.is_banned = False
    user_profile.save()
    return redirect(reverse("bulletin:view_profile", args=(pk,)))


def thread_first_page(request, pk):
    page = 1
    return redirect(reverse("bulletin:view_thread_page", args=(pk, page,)))


def board_first_page(request, pk):
    page = 1
    return redirect(reverse("bulletin:view_board_page", args=(pk, page,)))


def index_first_page(request):
    page = 1
    return redirect(reverse("bulletin:view_index_page", args=(page,)))


def profile_first_page(request, pk):
    page = 1
    return redirect(reverse("bulletin:view_profile_page", args=(pk, page,)))

francis_exam_onboarding/bulletin/templates/bulletin/create_board.html
{% extends 'base.html' %}

{%block head%}
    <title>Create Board</title>
{%endblock head%}

{%block body%}
    <div class='container'>
        <h1>Create Board</h1>
        <form method='post'>
            {% csrf_token %}
            {{form.as_p}}
            <button class='btn btn-default' type='submit'>Create</button>
        </form>
    </div>
{%endblock body%}

francis_exam_onboarding/bulletin/templates/bulletin/create_thread.html
{% extends 'base.html' %}

{%block head%}
    <title>Create Thread</title>
{%endblock head%}

{%block body%}
    <div class='container'>
        <h1>Create Thread</h1>
        <form method='post'>
            {% csrf_token %}
            {{form.as_p}}
            <button class='btn btn-default' type='submit'>Create</button>
        </form>
    </div>
{%endblock body%}

francis_exam_onboarding/bulletin/templates/bulletin/edit_board.html
{% extends 'base.html' %}

{%block head%}
    <title>Edit Board</title>
{%endblock head%}

{%block body%}
    <div class='container'>
        <h1>Edit Board</h1>
        <form method='post'>
            {% csrf_token %}
            {{form.as_p}}
            <button class='btn btn-default' type='submit'>Edit</button>
        </form>
    </div>
{%endblock body%}

francis_exam_onboarding/bulletin/templates/bulletin/edit_thread.html
{% extends 'base.html' %}

{%block head%}
    <title>Edit Thread</title>
{%endblock head%}

{%block body%}
    <div class='container'>
        <h1>Edit Thread</h1>
        <form method='post'>
            {% csrf_token %}
            {{form.as_p}}
            <button class='btn btn-default' type='submit'>Edit</button>
        </form>
    </div>
{%endblock body%}

francis_exam_onboarding/bulletin/templates/bulletin/home.html
{% extends 'base.html' %}

{% load bulletin_extras%}

{%block head%}
    <title>Home</title>
{%endblock head%}

{%block body%}
<div class='container'>
    {%if request.user|is_admin and not is_banned%}
        <a class='btn btn-success' href="{% url 'bulletin:create_board' %}">Create Board</a>
    {%endif%}
    <br/><br/>
    {{page_object}}<br/>
        {%for i in "x"|ljust:page_count%}
            {%if forloop.counter != page_number%}
                <a href="{% url 'bulletin:view_index_page' page=forloop.counter %}">{{forloop.counter}}</a>
            {%else%}
                [{{forloop.counter}}]
            {%endif%}
        {%endfor%}
    <form id="delete_board_form" action="{%url 'bulletin:delete_board'%}" method="post">
        {%csrf_token%}
    <input type="hidden" name="delete_board_id" id="delete_board_id"/>
    <table border='1' style='width:100%; border-collapse:collapse;'>
        <tr>
            <th colspan='3'><h3>Boards</h3></th>
        <tr>
        {%for board in page_object.object_list%}
            <tr>
                {%if request.user|is_admin and not is_banned%}
                    <td style='text-align:center;;width:10%'>
                        <a class='btn btn-warning' href="{%url 'bulletin:edit_board' board.id%}">Edit</a>
                    </td>
                    <td style='text-align:center;;width:10%'>
                        <button type="submit" class="btn btn-danger" onclick="change_delete_value({{board.id}})">Delete</button>
                    </td>
                {%endif%}
                <td>
                    <h4><a href="{%url 'bulletin:view_board' board.id%}">{{board.name}}</a></h4>
                    {%if board.get_recent_post%}
                        <a href="{%url 'bulletin:view_thread' board.get_recent_post.thread.id %}">{{board.get_recent_post.thread.title}}</a>
                    {%else%}
                        No post Yet..
                    {%endif%}
                    <br/>
                    Thread count: {{board.thread_set.count}}<br/>
                    Post count: {{board.post_set.count}}
                </td>
            <tr>
        {%empty%}
        <tr>
            <td colspan='3'>No boards found</td>
        </tr>
        {%endfor%}
    </table>
    </form>
</div>
{%endblock body%}

{%block scripts%}
    <script type="text/javascript">
        function change_delete_value(pk) {
            $("#delete_board_id").val(pk);
        }
    </script>
{%endblock scripts%}

francis_exam_onboarding/bulletin/templates/bulletin/login.html
{% extends 'base.html' %}

{%block head%}
    <title>Login</title>
{%endblock head%}

{%block body%}
    <div class='container'>
        <h1>Login</h1>
        <form method='post'>
            {% csrf_token %}
            {{form.as_p}}
            <button class='btn btn-default' type='submit'>Login</button>
        </form>
    </div>
{%endblock body%}

francis_exam_onboarding/bulletin/templates/bulletin/logout.html
{% extends 'base.html' %}

{%block head%}
    <title>Logout</title>
{%endblock head%}

{%block body%}
    <div class='container'>
        <h1>Logout</h1>
        <p>You have been logged out</p>
    </div>
{%endblock body%}

francis_exam_onboarding/bulletin/templates/bulletin/register.html
{% extends 'base.html' %}

{%block head%}
    <title>Register</title>
{%endblock head%}

{%block body%}
    <div class='container'>
        <h1>Register</h1>
        <form method='post'>
            {% csrf_token %}
            {{form.as_p}}
            <button class='btn btn-default' type='submit'>Register</button>
        </form>
    </div>
{%endblock body%}

francis_exam_onboarding/bulletin/templates/bulletin/view_board.html
{% extends 'base.html' %}

{%block head%}
    <title>View Board</title>
{%endblock head%}

{%block body%}
    <div class='container'>
        <h1>{{board.name}}</h1>
        {%if not is_banned%}
        <a class='btn btn-warning' href="{%url 'bulletin:create_thread' board.id%}">Create Thread</a>
        {%endif%}
        <br/>
        {{page_object}}<br/>
        {%for i in "x"|ljust:page_count%}
            {%if forloop.counter != page_number%}
                <a href="{% url 'bulletin:view_board_page' pk=board.pk page=forloop.counter %}">{{forloop.counter}}</a>
            {%else%}
                [{{forloop.counter}}]
            {%endif%}
        {%endfor%}
        <table border='1' style='width:100%; border-collapse:collapse;'>
        <tr>
            <th colspan='4'><h3>Threads</h3></th>
        <tr>
        {%for thread in page_object.object_list%}
            <tr>
                {%if thread.posted_by == user and not is_banned%}
                    <td style='text-align:center;;width:10%'>
                        <a class='btn btn-warning' href="{%url 'bulletin:edit_thread' thread.id%}">Edit</a>
                    </td>
                {%else%}
                    <td tyle='text-align:center;width:10%'></td>
                {%endif%}
                <td>
                    <h4>
                        <a href="{%url 'bulletin:view_thread' thread.id%}">{{thread.title}}</a>
                        {%if thread.is_locked%}
                        [LOCKED]
                        {%endif%}
                    </h4>
                    {%if thread.get_recent_post%}
                        Last Reply: {{thread.get_recent_post.posted_on}}<br>
                        Last Poster: <a href="/bulletin/profiles/{{thread.get_recent_poster_profile_id}}">
                            {{thread.get_recent_post.posted_by}}
                        </a>
                    {%else%}
                        No Post yet...
                    {%endif%}
                </td>
            <tr>
        {%empty%}
        <tr>
            <td colspan='4'>No threads found</td>
        <tr>
        {%endfor%}
    </table>
    </div>
{%endblock body%}

francis_exam_onboarding/bulletin/templates/bulletin/view_thread.html
{% extends 'base.html' %}

{%block head%}
    <title>View Board</title>
{%endblock head%}

{%block body%}
    <div class='container'>
        <h1>{{thread.board.name}}/{{thread.title}}</h1>
        <a href="{%url 'bulletin:view_board' thread.board.pk%}">Back to Boards...</a>
        <br/>
        {{page_object}}<br/>
        {%for i in "x"|ljust:page_count%}
            {%if forloop.counter != page_number%}
                <a href="{% url 'bulletin:view_thread_page' pk=thread.pk page=forloop.counter %}">{{forloop.counter}}</a>
            {%else%}
                [{{forloop.counter}}]
            {%endif%}
        {%endfor%}
        <table border='1' style='width:100%; border-collapse:collapse;'>
        <tr>
            <th colspan='4'><h3>Posts</h3></th>
        <tr>
        {%for post in page_object.object_list%}
            <tr>
                <td style='width:10%'>
                    From: 
                    {%if post.posted_by%}
                    <a href="{%url 'bulletin:view_profile' post.posted_by.id %}">{{post.posted_by}}</a>
                    {%endif%}
                    <br/>
                    Date Posted: {{post.posted_on}}
                </td>
                <td>{{post.message}}</td>
            </tr>
        {%endfor%}
        {%if not user.userprofile.is_banned%}
            {%if not thread.is_locked and page_number == page_count%}
            <tr>
                <td colspan=4 style='border-top:3px solid black'>
                    <form action="{%url 'bulletin:create_post' thread.pk%}" method="post">
                        {%csrf_token%}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Reply</button>
                    </form>
                </td>
            </tr>
            {%endif%}
        {%endif%}
    </table>
    </div>
{%endblock body%}

francis_exam_onboarding/bulletin/templates/bulletin/view_user_profile.html
{% extends 'base.html' %}

{% load bulletin_extras %}

{%block head%}
    <title>View User Profile</title>
{%endblock head%}

{%block body%}
    <div class='container'>
        <h1>{{user_profile.user}}</h1>
        First Name: {{user_profile.user.first_name}}<br/>
        Last Name: {{user_profile.user.last_name}}<br/>
        Banned?: {{user_profile.is_banned}}<br/>
        {%if not is_self%}
            {%if request.user|is_admin or request.user|is_mod%}
                {%if not user_profile.is_banned%} 
                <a class='btn btn-danger' href="{%url 'bulletin:set_user_ban' pk=user_profile.id is_ban='true' %}">Ban User</a>
                {%else%}
                <a class='btn btn-success' href="{%url 'bulletin:set_user_ban' pk=user_profile.id is_ban='false'%}">Unban User</a>
                {%endif%}
            {%endif%}
        {%endif%}
        {{page_object}}<br/>
        {%for i in "x"|ljust:page_count%}
            {%if forloop.counter != page_number%}
                <a href="{% url 'bulletin:view_profile_page' pk=user_profile.pk page=forloop.counter %}">{{forloop.counter}}</a>
            {%else%}
                [{{forloop.counter}}]
            {%endif%}
        {%endfor%}
        <table border='1' style='width:100%; border-collapse:collapse;'>
        <tr>
            <th colspan='4'><h3>Posts</h3></th>
        <tr>
        {%for post in page_object.object_list%}
            <tr>
                <td style='width:10%'>
                    Date Posted: {{post.posted_on}}
                </td>
                <td><a href="{%url 'bulletin:view_thread' post.thread.id%}">{{post.message}}</a></td>
            </tr>
        {%endfor%}
    </table>
    </div>
{%endblock body%}